### PR TITLE
Add JSHint config file

### PR DESCRIPTION
**Pull request by AndrewDaGuy**
[Configuration file documentation](https://jshint.com/docs/options/)

### CODE REVIEW

**Comment by DashCruft** [comment]
@BurnieBed What do you think 🤔

**Comment by BurnedBed** [comment]
Sorry, but we are not thinking about adding this any time soon

**Comment by BurnedBed** [comment]
I think eslint is more than enough.

**Comment by BurnedBed** [comment]
😳

**Comment by AndrewDaGuy** [comment]
> I think eslint is more than enough.

@BurnedBed Ah so this happens when I don't have the file:

image

**Pull request closed without merging**
