### PR TITLE
kick.js

### PR DESCRIPTION
**Pull request by birbsnest**
kick command made!

### CODE REVIEW

**Comment by DashCruft** [comment]
You have to make sure the command works without any problems before you commit.

Its a rule specified in here: https://github.com/DashCruft-Nation/DisCruft-Bot#readme

Let us know whether this works or not. If it doesn't or if there is any errors, commit the new changes here again.

**Comment by birbsnest** [comment]
> You have to make sure the command works without any problems before you commit.
> 
> Its a rule specified in here: https://github.com/DashCruft-Nation/DisCruft-Bot#readme
> 
> Let us know whether this works or not. If it doesn't or if there is any errors, commit the new changes here again.

dash srry k? its just i never used the module style so i asked

**Comment by DashCruft** [comment]
> > You have to make sure the command works without any problems before you commit.
> > Its a rule specified in here: https://github.com/DashCruft-Nation/DisCruft-Bot#readme
> > Let us know whether this works or not. If it doesn't or if there is any errors, commit the new changes here again.
> 
> dash srry k? its just i never used the module style so i asked

I'm not mad at you or anything! I'm here to just help :)

**Comment by birbsnest** [comment]
> > > You have to make sure the command works without any problems before you commit.
> > > Its a rule specified in here: https://github.com/DashCruft-Nation/DisCruft-Bot#readme
> > > Let us know whether this works or not. If it doesn't or if there is any errors, commit the new changes here again.
> > 
> > 
> > dash srry k? its just i never used the module style so i asked
> 
> I'm not mad at you or anything! I'm here to just help :)

k thnx!

**Comment by birbsnest** [comment]
sooo.... how do i properly use the module.exports.config?

**Comment by birbsnest** [comment]
@DashCruft  now it will work add it!

**Comment by DashCruft** [comment]
Thank you!

**Comment by BurnedBed** [comment]
words before disaster

**Pull request merged**
