### PR TITLE
Unban and purge command cuz why not

### PR DESCRIPTION
**Pull request by LegItMate**
If you want me to change anything I'll do it

### CODE REVIEW

**Comment by BurnedBed** [comment]
why u change prefix

**Comment by BurnedBed** [comment]
🤔

**Comment by GeneralHubertGaleforce** [comment]
Why you change 👎

**Comment by GeneralHubertGaleforce** [comment]
Hi people that sees this message lol

**Comment by LegItMate** [comment]
Ah dang wait

**Comment by LegItMate** [comment]
Aight done

**Comment by BurnedBed** [comment]
all tested, right?

**Comment by GeneralHubertGaleforce** [comment]
when new command

**Pull request merged**
