### PR TITLE
added colors, may not work :roll_eyes: 

### PR DESCRIPTION
**Pull request by ImFace**

### CODE REVIEW

**Comment by LegItMate** [comment]
a lot of errors :Man:

**Comment by ImFace** [comment]
:smirk: ayo bro first time

**Comment by LegItMate** [comment]
it said a rainbow though this is randomly shown 😐 
image

**Comment by ImFace** [comment]
i dont **get** it

**Comment by ImFace** [comment]
also juice cool

**Comment by ImFace** [comment]
close before someone see this

**Comment by LegItMate** [comment]
just commit the new changes again bro

**Comment by ImFace** [comment]
nou

**Comment by LegItMate** [comment]
?!?!?!?!?!?!

**Comment by ImFace** [comment]
no - no
u- do it your self

**Comment by LegItMate** [comment]
you do it or bad dev :trollface:

**Comment by ImFace** [comment]
fuck what to do

**Comment by DeadLordWasTaken** [comment]
fix eslint errors theres a shit ton

**Pull request closed without merging**
