### PR TITLE
Cat image command

### PR DESCRIPTION
**Pull request by ASOwnerYT**
Similar to my last pull request, but cat images instead of cat facts! Uses the Snowflake API.

### CODE REVIEW

**Comment by Assassin-1234** [comment]
are you sure you want to give your api key ?

**Comment by ASOwnerYT** [comment]
CRAP FORGOT TO REMOVE IT PLS NO HAX!!!1111

**Comment by ASOwnerYT** [comment]
All good I regenerated it, no hax for u

**Comment by Assassin-1234** [comment]
since its open-sourced, anyone can take the api key so I dont think this should go to the bot

**Comment by Mafia-7777** [comment]
or dash can add a env var

**Comment by Assassin-1234** [comment]
@DashCruft okeyga

**Comment by ASOwnerYT** [comment]
The catfact command has an API key in the code (my API key), so what's the difference here?

**Pull request closed without merging**
