### PR TITLE
All the changes in description and uh yea

### PR DESCRIPTION
**Pull request by LegItMate**
CHANGELOGS: (Long)
Transfered avatar, stats and delete.js
Changed some image commands
Changed ban, kick and clear command
Fixed slowmode not working with 0
Merged binary-decode and binary-encode into a single command
Added a confirmation to delete command(yikes)
Fixed cat command
Changed fart command
Added embed to monke command
Added mention prefix 😮 
----------------------------
Custom music system: (Removed distube)

Added resume, pause, volume, nowplaying 
Stop command now asks if you want to delete the queue or not!
Better queue embed
Changed embeds in play command

PLS CHECK THE CODE TKS

### CODE REVIEW

**Comment by LegItMate** [comment]
At last custom music system :ye:

**Comment by LegItMate** [comment]
**_This also includes cat cmd fix and slowmode cmd fix_**

**Comment by reconlx** [comment]
cool 👯

**Comment by LegItMate** [comment]
Recon 😮

**Pull request merged**
