### PR TITLE
Just a dice command

### PR DESCRIPTION
**Pull request by MrM0nkeyz**
Dice command that will generate a random number between 1 and 6

### CODE REVIEW

**Review by Assassin-1234 — COMMENTED** [review]
fix lint errors please, also will merge after legitmate's pull request because of conflicts

**Comment by BurnedBed** [comment]
conflicts?

**Comment by BurnedBed** [comment]
also the code could be written better @MrM0nkeyz

**Comment by MrM0nkeyz** [comment]
Yeah you are right.

**Comment by BurnedBed** [comment]
I am going to close this pr. We can get back to you once you got the updated code.

**Comment by MrM0nkeyz** [comment]
It's not an important command anyways so this doesn't need to be here.

**Comment by BurnedBed** [comment]
It's fine.

**Comment by LegItMate** [comment]
I am just checking some commands, so like 5 minutes or less ;-;

**Pull request closed without merging**
