### PR TITLE
howgae.js

### PR DESCRIPTION
**Pull request by birbsnest**
yeah new fun cmd add it it will be fun ngl

### CODE REVIEW

**Comment by LegItMate** [comment]
Correct teh aliase

**Comment by LegItMate** [comment]
And fix lint errors pls tks

**Comment by birbsnest** [comment]
@LegItMate  oi fixed now pull

**Comment by LegItMate** [comment]
Bro how will aliase have spaces and you still didn't fix lint errors

**Comment by birbsnest** [comment]
> Bro how will aliase have spaces and you still didn't fix lint errors

aight all fix now pull

**Comment by LegItMate** [comment]
Whys there 2 descriptions ??

**Comment by birbsnest** [comment]
aight playtime over

**Comment by LegItMate** [comment]
Bro do you even use lint, the errors weren't fixed still. I fixed them so anyways

**Comment by LegItMate** [comment]
I aint gonna push the commits anyone else can check it 🙄

**Comment by DeadLordWasTaken** [comment]
> I aint gonna push the commits anyone else can check it 🙄

I'll check it rn before I go to sleep

**Review by Assassin-1234 — COMMENTED** [review]
you can use a random function and choose from 1 - 100 as it would be more appropriate but sure looks good to me

**Comment by DashCruft** [comment]
You don't have a good past in making merges. 
I reject this without checking.

**Pull request closed without merging**
