### PR TITLE
Crated mometn.javascript

### PR DESCRIPTION
**Pull request by face-hh**
its always someone's moment :ye:

### CODE REVIEW

**Comment by LegItMate** [comment]
So whats this

**Comment by LegendaryEmoji** [comment]
> So whats this

idk lol i guess image manipulating command

**Comment by ImFace** [comment]
> > So whats this
> 
> idk lol i guess image manipulating command

guessing true

**Comment by LegItMate** [comment]
Did you change the size of pfp

**Comment by ImFace** [comment]
> Did you change the size of pfp

did you read this https://discord.com/channels/644764850706448384/739308495878488065/823856974264270878

**Comment by LegItMate** [comment]
I'll do it later till then keep this PR open

**Comment by BurnedBed** [comment]
ok

**Comment by Assassin-1234** [comment]
outdated

**Pull request closed without merging**
