### PR TITLE
Created epic ppsize command :ye:

### PR DESCRIPTION
**Pull request by namanop**

### CODE REVIEW

**Review by Assassin-1234 — COMMENTED** [review]
please fix the lint errors, will approve the pr after that

**Comment by BurnedBed** [comment]
^^^

**Comment by Assassin-1234** [comment]
:Man: I fixed it for you

**Comment by BurnedBed** [comment]
> :Man: I fixed it for you

why did you not put the file in fun?

**Comment by BurnedBed** [comment]
epic fixed

**Pull request merged**
