### PR TITLE
delete.js

### PR DESCRIPTION
**Pull request by birbsnest**
this might seem a bit stoopid but its actully not use this to delete channels in the server!

### CODE REVIEW

**Comment by DashCruft** [comment]
@BurnedBed Do you approve?

**Comment by birbsnest** [comment]
> @BurnedBed Do you approve?

lmao is that swagger?

**Comment by Rachniotov** [comment]
What do you think

**Comment by Assassin-1234** [comment]
it shouldnt require the administrator permission

**Comment by birbsnest** [comment]
> it shouldnt require the administrator permission

it doesnt anymore

**Comment by Assassin-1234** [comment]
its `MANAGE_CHANNELS` not `MANAGE_CHANNEL`

**Comment by birbsnest** [comment]
> its `MANAGE_CHANNELS` not `MANAGE_CHANNEL`

ok sht

**Pull request merged**
