### PR TITLE
Added math command

### PR DESCRIPTION
**Pull request by jebediah47**
This command takes a user's mathematical question and then solves it and sends it to the channel! Here's an example:
example

### CODE REVIEW

**Comment by jebediah47** [comment]
Can someone review the changes pls

**Review by Assassin-1234 — CHANGES_REQUESTED** [review]
fix quotes

**Comment by jebediah47** [comment]
> fix quotes 

do you mean in the args join?

**Comment by Assassin-1234** [comment]
> > fix quotes
> 
> do you mean in the args join?

quotes as in ""

**Comment by jebediah47** [comment]
> > > fix quotes
> > 
> > 
> > do you mean in the args join?
> 
> quotes as in ""

Ok fixed it

**Review by Assassin-1234 — APPROVED** [review]

**Comment by Assassin-1234** [comment]
kinda off topic but that wallpaper looks cool 😳can you send link?

**Comment by jebediah47** [comment]
> kinda off topic but that wallpaper looks cool 😳can you send link?

ok I will try to find it wait

**Comment by jebediah47** [comment]
> kinda off topic but that wallpaper looks cool 😳can you send link?

this is the repo with my wallpaper but it also has others in the same style that u may like https://github.com/pop-os/wallpapers/tree/master/original

**Comment by jebediah47** [comment]
Bruh when is this PR gonna be merged :joy:

**Comment by DashCruft** [comment]
Thanks for your patience <3 and sorry for the lack of activity.

Merged to the main branch.

**Pull request merged**
