### PR TITLE
Added ascii command.

### PR DESCRIPTION
**Pull request by jebediah47**
This command turns user's input to ascii text art here is an example of executing the command: 
this is the example gif

### CODE REVIEW

**Review by Assassin-1234 — CHANGES_REQUESTED** [review]
use eslint please.

**Comment by jebediah47** [comment]
> use eslint please.

Ok I commited the changes.

**Comment by Assassin-1234** [comment]
thats not how eslint works, make sure you have the eslint extension for vsc and then fix all the errors in the file.

**Review by Assassin-1234 — APPROVED** [review]

**Comment by jebediah47** [comment]
> thats not how eslint works, make sure you have the eslint extension for vsc and then fix all the errors in the file.
Oh ok I fixed them now.

**Comment by DashCruft** [comment]
Changes have been merged into the main branch.

Thank you @jebediah47 <3

**Pull request merged**
